name: Build & Test & Scan

permissions:
  issues: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  # ================== CI PIPELINE ==================
  ci_pipeline:
    name: Django CI + SonarCloud + Bandit
    runs-on: ubuntu-latest

    steps:
    # ------------------- CHECKOUT -------------------
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        fetch-depth: 0

    # ------------------- PYTHON SETUP -------------------
    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
      with:
        python-version: '3.12'

    # ------------------- INSTALL DEPENDENCIES -------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest pytest-django bandit

    # ------------------- RUN TESTS + COVERAGE -------------------
    - name: Run Django tests with coverage
      run: |
        coverage run manage.py test --verbosity=2
        coverage xml
        coverage report

    # Upload coverage file
    - name: Upload Coverage XML
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      with:
        name: coverage-xml
        path: coverage.xml

    # ------------------- BANDIT SECURITY SCAN -------------------
    - name: Run Bandit Security Scan
      run: bandit -r . -ll

    # ------------------- SONARCLOUD SCAN -------------------
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
      with:
        args: >
          -Dsonar.python.coverage.reportPaths=coverage.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarcloud.io"


  # ================== ZAP BASELINE SCAN ==================
  zap-scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: ci_pipeline

    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25
      with:
        target: "https://dublin-digs.onrender.com"
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_action: false
        cmd_options: >
          -a
          -m 0
          -T 5
        docker_name: ghcr.io/zaproxy/zaproxy:stable
        upload_artifact: false

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      with:
        name: zap-report
        path: |
          report_html.html
          report_md.md
          report_json.json
